Import patches-unapplied version 2.6.0~git20160810.7f5f2bd-0ubuntu1 to ubuntu/yakkety-proposed
Imported using git-ubuntu import.

Changelog parent: 63cc20212a51f701180797f637aab1fb231d7f79

New changelog entries:
  * New upstream snapshot for 2.6.0 release goal.
  * d/control: Bumped Standards-Version to 3.9.8, no changes.
  * d/openvswitch-common.install: Drop ovs-benchmark tool, removed upstream
    due to lack of use and maintenance.
  * d/control,ovn-controller-vtep.*: Add ovn-controller-vtep package.
  * d/openvswitch-switch.install: Add ovs-tcpdump binary and manpage.
  * Add support for Python 3:
    - d/control: Drop surplus Python 2 BD's, add BD's for Python 3.
    - d/control: Add missing dependency on python-six.
    - d/rules,control: Add python3-openvswitch package.
  * d/rules: Skip racey/failing tests until resolved upstream.

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -73,6 +73,7 @@ docs = \
 	INSTALL.md \
 	INSTALL.Debian.md \
 	INSTALL.Docker.md \
+	INSTALL.DPDK-ADVANCED.md \
 	INSTALL.DPDK.md \
 	INSTALL.Fedora.md \
 	INSTALL.KVM.md \
@@ -85,6 +86,7 @@ docs = \
 	INSTALL.userspace.md \
 	INSTALL.Windows.md \
 	IntegrationGuide.md \
+	MAINTAINERS.md \
 	OPENFLOW-1.1+.md \
 	PORTING.md \
 	README.md \
@@ -92,25 +94,28 @@ docs = \
 	README-native-tunneling.md \
 	REPORTING-BUGS.md \
 	SECURITY.md \
-	TODO.md \
 	WHY-OVS.md
 EXTRA_DIST = \
 	$(docs) \
 	NOTICE \
 	.travis.yml \
-	.travis/build.sh \
-	.travis/prepare.sh \
+	.travis/linux-build.sh \
+	.travis/linux-prepare.sh \
+	.travis/osx-build.sh \
+	.travis/osx-prepare.sh \
 	appveyor.yml \
 	boot.sh \
 	build-aux/cccl \
 	build-aux/cksum-schema-check \
+	build-aux/calculate-schema-cksum \
 	build-aux/dist-docs \
 	build-aux/sodepends.pl \
 	build-aux/soexpand.pl \
 	build-aux/xml2nroff \
 	$(MAN_FRAGMENTS) \
 	$(MAN_ROOTS) \
-	Vagrantfile
+	Vagrantfile \
+	Vagrantfile-FreeBSD
 bin_PROGRAMS =
 sbin_PROGRAMS =
 bin_SCRIPTS =
@@ -142,6 +147,7 @@ SUFFIXES =
 check_DATA =
 check_SCRIPTS =
 pkgconfig_DATA =
+FLAKE8_PYFILES =
 
 scriptsdir = $(pkgdatadir)/scripts
 completiondir = $(sysconfdir)/bash_completion.d
@@ -183,6 +189,7 @@ SUFFIXES += .in
 SUFFIXES += .xml
 %: %.xml
 	$(AM_V_GEN)$(run_python) $(srcdir)/build-aux/xml2nroff $< > $@.tmp \
+		-I $(srcdir) \
 		--version=$(VERSION) \
 		PKIDIR='$(PKIDIR)' \
 		LOGDIR='$(LOGDIR)' \
@@ -245,7 +252,7 @@ config-h-check:
 	@cd $(srcdir); \
 	if test -e .git && (git --version) >/dev/null 2>&1 && \
 	   git --no-pager grep -L '#include <config\.h>' `git ls-files | grep '\.c$$' | \
-               grep -vE '^datapath|^lib/sflow|^third-party|^datapath-windows'`; \
+               grep -vE '^datapath|^lib/sflow|^third-party|^datapath-windows|^python'`; \
 	then \
 	    echo "See above for list of violations of the rule that"; \
 	    echo "every C source file must #include <config.h>."; \
@@ -340,6 +347,36 @@ manpage-check: $(man_MANS) $(dist_man_MANS) $(noinst_man_MANS)
 CLEANFILES += manpage-check
 endif
 
+if HAVE_FLAKE8
+ALL_LOCAL += flake8-check
+# http://flake8.readthedocs.org/en/latest/warnings.html
+# All warnings explicitly selected or ignored should be listed below.
+#
+# E***, W*** -- warnings from pep8
+#   E121 continuation line under-indented for hanging indent (only from flake8 v2.0)
+#   E123 closing bracket does not match indentation of opening bracket's line
+#   E125 continuation line with same indent as next logical line (only from flake8 v2.0)
+#   E126 continuation line over-indented for hanging indent
+#   E127 continuation line over-indented for visual indent
+#   E128 continuation line under-indented for visual indent
+#   E129 visually indented line with same indent as next logical line
+#   E131 continuation line unaligned for hanging indent
+#   W503 line break before binary operator
+# F*** -- warnings native to flake8
+#   F811 redefinition of unused <name> from line <N> (only from flake8 v2.0)
+# D*** -- warnings from flake8-docstrings plugin
+# H*** -- warnings from flake8 hacking plugin (custom style checks beyond PEP8)
+#   H231 Python 3.x incompatible 'except x,y:' construct
+#   H232 Python 3.x incompatible octal 077 should be written as 0o77
+#   H233 Python 3.x incompatible use of print operator
+#   H238 old style class declaration, use new style (inherit from `object`)
+flake8-check: $(FLAKE8_PYFILES)
+	$(AM_V_GEN) if flake8 $^ --select=H231,H232,H233,H238 ${FLAKE8_FLAGS} && \
+		flake8 $^ --ignore=E121,E123,E125,E126,E127,E128,E129,E131,W503,F811,D,H ${FLAKE8_FLAGS}; then \
+		touch $@; else exit 1; fi
+endif
+CLEANFILES += flake8-check
+
 include $(srcdir)/manpages.mk
 $(srcdir)/manpages.mk: $(MAN_ROOTS) build-aux/sodepends.pl
 	@$(PERL) $(srcdir)/build-aux/sodepends.pl -I. -I$(srcdir) $(MAN_ROOTS) >$(@F).tmp
@@ -352,17 +389,24 @@ $(srcdir)/manpages.mk: $(MAN_ROOTS) build-aux/sodepends.pl
 CLEANFILES += manpage-dep-check
 
 if VSTUDIO_DDK
-ALL_LOCAL += ovsext_make
-ovsext_make: datapath-windows/ovsext.sln
-	MSBuild.exe datapath-windows/ovsext.sln /target:Build /property:Configuration="Win8$(VSTUDIO_CONFIG)"
-	MSBuild.exe datapath-windows/ovsext.sln /target:Build /property:Configuration="Win8.1$(VSTUDIO_CONFIG)"
+ALL_LOCAL += ovsext
+ovsext: datapath-windows/ovsext.sln $(srcdir)/datapath-windows/include/OvsDpInterface.h
+	MSBuild.exe //maxcpucount datapath-windows/ovsext.sln /target:Build /property:Configuration="Win8$(VSTUDIO_CONFIG)"
+	MSBuild.exe //maxcpucount datapath-windows/ovsext.sln /target:Build /property:Configuration="Win8.1$(VSTUDIO_CONFIG)"
 
 CLEAN_LOCAL += ovsext_clean
 ovsext_clean: datapath-windows/ovsext.sln
-	MSBuild.exe datapath-windows/ovsext.sln /target:Clean /property:Configuration="Win8$(VSTUDIO_CONFIG)"
-	MSBuild.exe datapath-windows/ovsext.sln /target:Clean /property:Configuration="Win8.1$(VSTUDIO_CONFIG)"
+	MSBuild.exe //maxcpucount datapath-windows/ovsext.sln /target:Clean /property:Configuration="Win8$(VSTUDIO_CONFIG)"
+	MSBuild.exe //maxcpucount datapath-windows/ovsext.sln /target:Clean /property:Configuration="Win8.1$(VSTUDIO_CONFIG)"
 endif
-.PHONY: ovsext_make
+.PHONY: ovsext
+
+clang-analyze: clean
+	@which clang scan-build >/dev/null 2>&1 || \
+		(echo "Unable to find clang/scan-build, Install clang,clang-analyzer packages"; exit 1)
+	@$(MKDIR_P) "$(srcdir)/tests/clang-analyzer-results"
+	@scan-build -o $(srcdir)/tests/clang-analyzer-results --use-cc=$(CC) $(MAKE)
+.PHONY: clang-analyze
 
 dist-hook: $(DIST_HOOKS)
 all-local: $(ALL_LOCAL)
@@ -377,7 +421,7 @@ if LINUX_ENABLED
 endif
 
 dist-docs:
-	VERSION=$(VERSION) $(srcdir)/build-aux/dist-docs $(srcdir) $(docs)
+	VERSION=$(VERSION) MAKE='$(MAKE)' $(srcdir)/build-aux/dist-docs $(srcdir) $(docs)
 .PHONY: dist-docs
 
 include Documentation/automake.mk
diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -3,7 +3,7 @@
 #export DH_VERBOSE=1
 
 %:
-	dh $@ --with autoreconf,python2,systemd --parallel
+	dh $@ --with autoreconf,python2,python3,systemd --parallel
 
 # use --as-needed only if supported by dh-autoreconf (to simplify backporting)
 DH_AS_NEEDED=$(shell dpkg --compare-versions $$(dpkg --status dh-autoreconf | grep Version | cut -d' ' -f2) ge 6 && echo --as-needed)
@@ -16,6 +16,9 @@ else
 PARALLEL =
 endif
 
+PYTHONS:=$(shell pyversions -vr)
+PYTHON3S:=$(shell py3versions -vr)
+
 override_dh_auto_configure:
 	test -d _debian || mkdir _debian
 	cd _debian && ( \
@@ -27,8 +30,16 @@ ifneq (,$(filter i386 amd64, $(DEB_HOST_ARCH)))
 	cd _dpdk && ( \
 		test -e Makefile || \
         ../configure --prefix=/usr --localstatedir=/var --enable-ssl \
-                     --with-dpdk=/usr --sysconfdir=/etc \
+                     --with-dpdk --sysconfdir=/etc \
 					 $(DATAPATH_CONFIGURE_OPTS))
+endif
+
+
+# Skip some known failing tests - review for each snapshot or release
+# https://bugs.launchpad.net/ubuntu/+source/openvswitch/+bug/1609846
+SKIP_TEST := 1-14 16-
+ifeq (i386, $(DEB_HOST_ARCH))
+SKIP_TEST := 1-14 16-1148 1150-2215 2217-
 endif
 
 override_dh_auto_test:
@@ -37,14 +48,14 @@ override_dh_auto_test:
 # is resolved
 ifeq (,$(filter powerpc s390x,$(DEB_HOST_ARCH)))
 ifeq (,$(filter nocheck,$(DEB_BUILD_OPTIONS)))
-	if $(MAKE) -C _debian check TESTSUITEFLAGS='$(PARALLEL)' || \
+	if $(MAKE) -C _debian check TESTSUITEFLAGS='$(PARALLEL) $(SKIP_TEST)' || \
                 $(MAKE) -C _debian check TESTSUITEFLAGS='--recheck'; then :; \
 	else \
 		cat _debian/tests/testsuite.log; \
 		exit 1; \
 	fi
 ifneq (,$(filter i386 amd64, $(DEB_HOST_ARCH)))
-	if $(MAKE) -C _dpdk check TESTSUITEFLAGS='$(PARALLEL)' || \
+	if $(MAKE) -C _dpdk check TESTSUITEFLAGS='$(PARALLEL) $(SKIP_TEST)' || \
 				$(MAKE) -C _dpdk check TESTSUITEFLAGS='--recheck'; then :; \
 	else \
 		cat _dpdk/tests/testsuite.log; \
@@ -74,6 +85,14 @@ override_dh_install:
 	mkdir -p $(CURDIR)/debian/openvswitch-switch/usr/lib/openvswitch-switch
 	mv $(CURDIR)/debian/openvswitch-switch/usr/sbin/ovs-vswitchd \
 		$(CURDIR)/debian/openvswitch-switch/usr/lib/openvswitch-switch/ovs-vswitchd
+	set -e && for pyvers in $(PYTHONS); do \
+		cd python && python$$pyvers setup.py install --install-layout=deb \
+			--root $(CURDIR)/debian/python-openvswitch; \
+	done
+	set -e && for pyvers in $(PYTHON3S); do \
+        cd python && python$$pyvers setup.py install --install-layout=deb \
+            --root $(CURDIR)/debian/python3-openvswitch; \
+    done
 ifneq (,$(filter i386 amd64, $(DEB_HOST_ARCH)))
 	install -D _dpdk/vswitchd/ovs-vswitchd \
         $(CURDIR)/debian/openvswitch-switch-dpdk/usr/lib/openvswitch-switch-dpdk/ovs-vswitchd-dpdk
@@ -90,15 +109,15 @@ override_dh_strip:
 # Helper target for creating snapshots from upstream git
 DATE=$(shell date +%Y%m%d)
 # Upstream branch to track
-BRANCH=branch-2.5
+BRANCH=master
+VERSION=2.6.0
 
 get-orig-snapshot:
 	rm -Rf openvswitch-upstream
 	git clone https://github.com/openvswitch/ovs openvswitch-upstream
 	cd openvswitch-upstream && \
-		git checkout -b $(BRANCH) remotes/origin/$(BRANCH) && \
+		git checkout $(BRANCH) && \
 		export COMMIT=`git rev-parse --short HEAD` && \
-		export UPSTREAM_VERSION=`head -1 NEWS | awk '{ print $$1 }' | sed 's/v//'` && \
-		git archive --format tgz --prefix=openvswitch-$$UPSTREAM_VERSION+git$(DATE)/ \
-			-o ../../openvswitch_$$UPSTREAM_VERSION~git$(DATE).$$COMMIT.orig.tar.gz $(BRANCH)
+		git archive --format tgz --prefix=openvswitch-$(VERSION)~git$(DATE).$$COMMIT/ \
+			-o ../../openvswitch_$(VERSION)~git$(DATE).$$COMMIT.orig.tar.gz $(BRANCH)
 	rm -Rf openvswitch-upstream
