Import patches-unapplied version 2.10.0-0ubuntu1 to ubuntu/cosmic-proposed
Imported using git-ubuntu import.

Changelog parent: ad8e3894315c4f6122e3fb131bc5d3e77fa4782c

New changelog entries:
  * d/control: Add BD on python{3}-sortedcontainers.
  * d/watch: Update for upstream website changes.
  * New upstream release.
  * d/p/py3-compat.patch: Rebased on latest upstream review.
  * d/rules: Disable tests 805,810,814 on s390x.
  * d/rules: Rename SKIP_TEST -> TEST_LIST.
  * d/rules: Re-enable all tests on arm64/armhf.
  * d/control: Add libunbound-dev to BD's.

diff --git a/tests/atlocal.in b/tests/atlocal.in
--- a/tests/atlocal.in
+++ b/tests/atlocal.in
@@ -1,11 +1,16 @@
 # -*- shell-script -*-
 HAVE_OPENSSL='@HAVE_OPENSSL@'
 HAVE_PYTHON='@HAVE_PYTHON@'
+HAVE_PYTHON2='@HAVE_PYTHON2@'
 HAVE_PYTHON3='@HAVE_PYTHON3@'
 EGREP='@EGREP@'
 
 if test x"$PYTHON" = x; then
     PYTHON='@PYTHON@'
+fi
+
+if test x"$PYTHON2" = x; then
+    PYTHON2='@PYTHON2@'
 fi
 
 if test x"$PYTHON3" = x; then
@@ -106,15 +111,32 @@ FreeBSD|NetBSD)
     ;;
 esac
 
-# Check whether to run IPv6 tests.
-if $PYTHON -c '
-import socket
-socket.socket(family=socket.AF_INET6).bind(("::1", 0, 0, 0))
-'; then
-    HAVE_IPV6=yes
-else
-    HAVE_IPV6=no
+if test x"$PYTHON3" != x && test "$IS_WIN32" = yes; then
+    # enables legacy windows unicode printing needed for Python3 compatibility
+    # with the Python2 tests
+    PYTHONLEGACYWINDOWSFSENCODING=true
+    export PYTHONLEGACYWINDOWSFSENCODING
+    PYTHONLEGACYWINDOWSSTDIO=true
+    export PYTHONLEGACYWINDOWSSTDIO
 fi
+
+# Check whether to run IPv6 tests.
+$PYTHON -c '
+import errno
+import socket
+import sys
+try:
+    socket.socket(family=socket.AF_INET6).bind(("::1", 0, 0, 0))
+except socket.error as e:
+    if e.errno == errno.EAFNOSUPPORT or errno.EADDRNOTAVAIL:
+        sys.exit(2)
+    raise
+'
+case $? in
+    0) HAVE_IPV6=yes ;;
+    2) HAVE_IPV6=no ;;
+    *) echo "$0: unexpected error probing $PYTHON for IPv6 support" >&2 ;;
+esac
 
 # Look for a python L7 library 'LIB' in the system. If it is found, defines
 # HAVE_LIB="yes", otherwise HAVE_LIB="no"
@@ -186,3 +208,7 @@ unset HTTP_PROXY
 unset HTTPS_PROXY
 unset FTP_PROXY
 unset NO_PROXY
+
+# Avoid OVN environment variables leaking in from external environment.
+unset OVN_NB_DB
+unset OVN_SB_DB
