Import patches-unapplied version 1.4.0+git20120321-1 to debian/sid
Imported using git-ubuntu import.

Changelog parent: 13662ff44f71047e71211d15319c68b8cfed1e88

New changelog entries:
  * New upstream version including:
    o Features:
      - ovs-vsctl: Allow "fake bridges" to be created for VLAN 0.
      - vswitchd: Make the MAC entry aging time configurable.
      - mac-learning: Increase MAC learning timeout to 300 seconds.
    o Bug fixes:  
      - netdev-linux: Fix use-after-free when netdev_dump_queues() deletes
        queues.
      - netlink-socket: Increase Netlink socket receive buffer size.
      - ofproto: Fix code that keeps track of MTU.
      - ovs-monitor-ipsec: Detect correctly IPSEC configuration changes
      - bond: Incorrectly reported an error in appctl.
      - socket-util: Unlink Unix domain sockets that bind but fail to connect.
      - bridge: Remove unwanted ports at time of ofproto creation.
      - dpif-linux: Make dpif_linux_port_query_by_name() query only one
        datapath.
      - ofproto-dpif: Cleanup STP on ports when disabled on their bridge.
      - configure: Try to extract kernel source directory from build Makefile.
      - vswitchd: Always configure a default queue for QoS.
      - ofproto-dpif: Don't output to in_port even if in_port is OFPP_LOCAL.
      - sflow_agent: Use snprintf() in place of sprintf().
    o Packaging:
      - Move PKI directory to FHS-compliant location.  Closes: #661090.
        Thanks to Andreas Beckmann <debian@abeckmann.de> for reporting
        this bug.
      - Use a different way to avoid failing install without kernel module.
      - Avoid unit test failure when doing "unofficial" builds.
      - Bump standards-version to 3.9.3.
      - Remove some useless files from the dkms package.
      - Clean .pyc files in "clean" target.
      - Remove po-debconf build dependency.
      - Build-depend on python-all to pull in all Python versions.
      - Add missing ${python:Depends} to openvswitch-test package.
      - Improve long descriptions so as to better describe the packages.
      - Bump debhelper compat level to 8 and make build-depends consistent.
      - Fix exit status of openvswitch-switch init script "status" command.
      - Use provided kernel source dir instead of host kernel version.
      - Do not run "make" if "configure" fails during DKMS build.
      - Look in /lib/modules instead of /usr/src for DKMS kernel sources.
      - Fix dependencies for openvswitch-datapath-dkms package.
      - Don't install Python modules for obsolete Python versions.
      - Add dependency on ${misc:Depends} to openvswitch-test
    o Documentation improvements:
      - ovsdb-doc: Use minus sign in negative numbers in nroff output.
      - ovsdb-doc: Convert '-' preceding a number as a minus sign, not a
        hyphen.
      - ovsdb-doc: Put NAME section into generated manpage.
      - Fix typo in manpage.
      - vswitchd: Document behavior of 802.1p priorities with VLAN splinters.
      - netdev: Fix typo in error message.
      - INSTALL.Linux: minor typo
  * Many thanks to Thomas Goirand <zigo@debian.org> for contributing many
    of the packaging fixes listed above.
  * This version fixes most of the lintian errors described in bug
    #663051, but a few remain, so this upload does not close that bug.  I
    believe that this upload should be suitable for downgrading that bug's
    severity.

diff --git a/debian/openvswitch-switch.init b/debian/openvswitch-switch.init
--- a/debian/openvswitch-switch.init
+++ b/debian/openvswitch-switch.init
@@ -1,6 +1,6 @@
 #! /bin/sh
 #
-# Copyright (C) 2011 Nicira Networks, Inc.
+# Copyright (C) 2011, 2012 Nicira Networks, Inc.
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
@@ -56,6 +56,13 @@ start () {
             echo "For instructions, read"
 	fi
 	echo "/usr/share/doc/openvswitch-datapath-source/README.Debian"
+
+	if test X"$OVS_MISSING_KMOD_OK" = Xyes; then
+	    # We're being invoked by the package postinst.  Do not
+	    # fail package installation just because the kernel module
+	    # is not available.
+	    exit 0
+	fi
     fi
     set ovs_ctl ${1-start} --system-id=random
     if test X"$FORCE_COREFILES" != X; then
@@ -86,6 +93,7 @@ case $1 in
         ;;
     status)
         ovs_ctl status
+        exit $?
         ;;
     force-reload-kmod)
         start force-reload-kmod
